package com.example.telecomunicaciones;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class V_ComercialIncidencias extends VerticalLayout {
	protected TabSheet menuTabCliente;
	protected VerticalLayout verticalPanel;
	protected Grid tableIncidenciasG;
	protected VerticalLayout verticalPanel2;
	protected Grid tableIncidenciasLL;
	protected Button nuevaIncidenciaBtn;

	public V_ComercialIncidencias() {
		Design.read(this);
	}
}
